# Jekyll GH-pages Digital Collection Generator

# Site settings
title: UI Web Archive Collections
description: Preserving access to unique born-digital content
keywords: university of idaho, university communications, digital collections, web archive
owner: University of Idaho Library
email: ewilliamson@uidaho.edu

# url variables
url: https://www.lib.uidaho.edu
baseurl: /digital/webarchive
liburl: https://www.lib.uidaho.edu
digurl: https://www.lib.uidaho.edu/digital
repourl: https://digital.lib.uidaho.edu

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
